### ISSUE TITLE
Get mediaWiki Error: Class "MWStake\MediaWiki\Component\ProcessManager\ProcessManager" not found

### ISSUE THREAD

**Issue by localtux** [hallowelt/mwstake-mediawiki-component-processmanager#10]
I have installed mediaWiki with version 1.39 LTS together with the extension "Page Forms" and the "Cognitive Process Designer".

The wiki of the Cognitive Process Designer says that you should enter this command in the terminal for the background service:

`php extensions/CognitiveProcessDesigner/vendor/mwstake/mediawiki-component-processmanager/maintenance/processRunner.php maintenance/Maintenance.php --wait`

Unfortunately, I get the following errors when I do this:

```
php extensions/CognitiveProcessDesigner/vendor/mwstake/mediawiki-component-processmanager/maintenance/processRunner.php maintenance/Maintenance.php --wait
[f84ac3ccf60395c0b4824c20] [no req]   Error: Class "MWStake\MediaWiki\Component\ProcessManager\ProcessManager" not found
Backtrace:
from /var/www/html/mediawiki/extensions/CognitiveProcessDesigner/vendor/mwstake/mediawiki-component-processmanager/maintenance/processRunner.php(31)
#0 /var/www/html/mediawiki/maintenance/includes/MaintenanceRunner.php(309): ProcessRunner->execute()
#1 /var/www/html/mediawiki/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#2 /var/www/html/mediawiki/extensions/CognitiveProcessDesigner/vendor/mwstake/mediawiki-component-processmanager/maintenance/processRunner.php(157): require_once(string)
#3 {main}
```

I have called the given command. I expect the background service to start.

**Comment by it-spiderman** [comment]
seems like this component is not properly added to your vendor directory. Either its completely missing or not part of the composer autoloader.

Unless you installed CognitiveProcessDesigner using compsoer, you will need to add this component to your {MWROOT}/composer.local.json and run composer update
